spring:
  jpa:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db?useSSL=false&allowPublicKeyRetrieval=true
    username: sampleuser
    password: password
  social:
    facebook:
      app-id: 339590223298588
      app-secret: 80e4c30063b07f1d4023f92216d546c0
    twitter:
      app-id: C8m4aDDH6Y5WEWK6HFg0FJSNb
      app-secret: sqbv2jWuu30h05uBvHsNY9UJprlNVq6wVRqCCNcSnXOjhzVQZa
    google:
      app-id: a
      app-secret: b
    line:
      app-id: a
      app-secret: b
