spring:
  jpa:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db?useSSL=false&allowPublicKeyRetrieval=true
    username: sampleuser
    password: password
  social:
    facebook:
      app-id: 1299326030235165
      app-secret: d4cb89607a09ea10ed29769c6021d59b
    twitter:
      app-id: C8m4aDDH6Y5WEWK6HFg0FJSNb
      app-secret: sqbv2jWuu30h05uBvHsNY9UJprlNVq6wVRqCCNcSnXOjhzVQZa
    google:
      app-id: a
      app-secret: b
    line:
      app-id: a
      app-secret: b
